### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by trevthedev777** [trevthedev777/Liseth-Spanish-School#18]
Using Dev Tools:

Create responsive design that will be compatible with all major devices and screen sizes for smaller screens including mobile

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue. :)

**Comment by trevthedev777** [comment]
Please create a pull request

**Comment by trevthedev777** [comment]
> Hey, I would like to work on this issue. :)

I have assigned the issue to you, if you can refactor any mistakes you see as well, that would help :)

**Comment by abitsalihu** [comment]
@trevthedev777 close this issue since it's resolved :)

**Comment by trevthedev777** [comment]
I will. Haven't had a moment to
